### ISSUE TITLE
Centering x-axis on 0 of y-axis

### ISSUE THREAD

**Issue by pkhxcp** [lumean/svg-graph2#3]
Is it possible to place the x-axis on the 0 of the y-axis? Attached is the issue I'm running into.

Right now, the y-axis is placed on the least value of the x-axis.
![example](https://cloud.githubusercontent.com/assets/7097300/20543476/f43642ee-b0d3-11e6-8e1e-7bcbc4b00211.png)

**Comment by lumean** [comment]
Hi, currently it is not possible. This will require some new options to be introduced. I think it would make sense to do the same feature also for the x-Axis (pin it on a certain value). Probably I can work on this some time next week.

**Comment by lumean** [comment]
pinning the axis to a certain x- or y- value requires some more work than expected. What I did so far, mostly because it was quick, is to introduce a parameter that allowes relative placement of the axis on the graph (from 0 to 1, where 0 is bottom and 1 is top) but I see that it doesn't make too much sense. Due to the autoscaling of the graph we can never really know to which value the relative position corresponds.

**Comment by lumean** [comment]
will release a new version the next days, beta is available. 
```
gem install svg-graph --pre
```
see https://github.com/lumean/svg-graph2/blob/master/History.txt  
and example: https://github.com/lumean/svg-graph2/blob/master/examples/plot.rb
